// const os = require(`${process.env.HOME}/.0/os/module`);
const sh = require('sh');

const choices = [
  1,
  2,
  3,
  'pe',
  'n',
  'r',
  's',
  't',
  'r 120vac',
  's 120vac',
  't 120vac',
  '230vac',
  '0/230vac',
  '24vac',
  '0/24vac',
  '24vdc',
  '0/24vdc',
  '12vdc',
  '0/12vdc',
  '5vdc',
  '0/5vdc',
  'di 230vac',
  'di 0vac',
  'di 24vac',
  'di 0/24vac',
  'di 24vdc',
  'di 0/24vdc',
  'di 12vdc',
  'di 0/12vdc',
  'di 5vdc',
  'di 0/5vdc',
  'do 24vdc',
  'do 0vdc',
  'do 12vdc',
  'do 0/12vdc',
  'do 5vdc',
  'do 0/5vdc',
  'rly 230vac',
  'rly 0/230vac',
  'rly 24vac',
  'rly 0/24vac',
  'rly 24vdc',
  'rly 0vdc',
  'rly 12vdc',
  'rly 0/12vdc',
  'rly 5vdc',
  'rly 0/5vdc',
  'ai 0...20ma',
  'ai 0...10vdc',
  'ai 0...5vdc',
  'ao 0...20ma',
  'ao 0...10vdc',
  'ao 0...5vdc',
  'rtd m+',
  'rtd i+',
  'rtd m-',
  'rtd i-',
];

sh.fzf({
  type: 'list-multi',
  message: 'Value:',
  // header: 'min: 0, max: 100',
  header: 'index|περιγραφή',
  choices: choices.map((choice, index) => [
    `${index}|${choice}`,
    index + 100,
    `{"paok":"nai","aris":${index}}`,
  ]),
  // choices: choices.map((choice, index) => `${choice}|${index}|preview: ${index}`),
  // choices,
  // choices: ['-vim-', 66, 99, 101],
  // preset: 'paok',
  // validation: (value) => (value > 0 && value <= 100) || value === 'paok ole' || value === '',

  height: '90%',
  enter: () => ({ value: '-retry-', text: sh.red('hello') }),
  esc: () => ({ value: 'paok', text: sh.red('esc for paok') }),
});
